// User/Auth
export const AUTH_ERROR = "AUTH_ERROR";
export const USER_LOADED = "USER_LOADED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

// Tasks
export const FETCH_TASKS = "FETCH_TASKS";
export const FETCH_TASKS_ERROR = "FETCH_TASKS_ERROR";
export const ADD_TASK = "ADD_TASK";
export const ADD_TASK_ERROR = "ADD_TASK_ERROR";
export const CLEAR_TASKS = "CLEAR_TASKS";
export const COMPLETE_TASK = "COMPLETE_TASK";
export const COMPLETE_TASK_ERROR = "COMPLETE_TASK_ERROR";
export const DELETE_TASK = "DELETE_TASK";
export const DELETE_TASK_ERROR = "DELETE_TASK_ERROR";
export const SET_CURRENT_TASK = "SET_CURRENT_TASK";
export const CLEAR_CURRENT_TASK = "CLEAR_CURRENT_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const UPDATE_TASK_ERROR = "UPDATE_TASK_ERROR";

// View
export const OPEN_SIDEBAR = "OPEN_SIDEBAR";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
export const OPEN_TASK_FORM = "OPEN_TASK_FORM";
export const CLOSE_TASK_FORM = "CLOSE_TASK_FORM";

// Projects
export const ADD_PROJECT = "ADD_PROJECT";
export const ADD_PROJECT_ERROR = "ADD_PROJECT_ERROR";
export const FETCH_PROJECTS = "FETCH_PROJECTS";
export const FETCH_PROJECTS_ERROR = "FETCH_PROJECTS_ERROR";
export const CLEAR_PROJECTS = "CLEAR_PROJECTS";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const DELETE_PROJECT_ERROR = "DELETE_PROJECT_ERROR";
